CREATE TABLE "users" (
                         "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         "username" varchar UNIQUE NOT NULL,
                         "password_hash" varchar NOT NULL,
                         "role" varchar NOT NULL CHECK (role IN ('ADMIN', 'DOCTOR', 'RECEPTIONIST')),
                         "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "doctors" (
                           "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           "user_id" bigint NOT NULL,
                           "full_name" varchar NOT NULL,
                           "specialization" varchar,
                           "phone" varchar NOT NULL
);

CREATE TABLE "patients" (
                            "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            "full_name" varchar NOT NULL,
                            "dob" date,
                            "sex" varchar NOT NULL,
                            "phone" varchar,
                            "address" varchar NOT NULL,
                            "blood_group" varchar,
                            "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "appointments" (
                                "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                "patient_id" bigint NOT NULL,
                                "doctor_id" bigint NOT NULL,
                                "appointment_datetime" timestamp NOT NULL,
                                "status" varchar NOT NULL CHECK (status IN ('SCHEDULED', 'COMPLETED', 'CANCELLED')),
                                "notes" varchar,
                                "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "invoices" (
                            "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            "patient_id" bigint NOT NULL,
                            "appointment_id" bigint,
                            "total_amount" numeric(10, 2),
                            "status" varchar NOT NULL CHECK (status IN ('PAID','UNPAID')),
                            "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "invoice_items" (
                                 "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 "invoice_id" bigint NOT NULL,
                                 "description" varchar NOT NULL,
                                 "amount" numeric(10, 2) NOT NULL
);

COMMENT ON COLUMN "users"."role" IS 'ADMIN, DOCTOR, RECEPTIONIST';

COMMENT ON COLUMN "appointments"."status" IS 'SCHEDULED, COMPLETED, CANCELLED';

COMMENT ON COLUMN "invoices"."status" IS 'PAID, UNPAID';

ALTER TABLE "doctors" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "appointments" ADD FOREIGN KEY ("patient_id") REFERENCES "patients" ("id");

ALTER TABLE "appointments" ADD FOREIGN KEY ("doctor_id") REFERENCES "doctors" ("id");

ALTER TABLE "invoices" ADD FOREIGN KEY ("patient_id") REFERENCES "patients" ("id");

ALTER TABLE "invoices" ADD FOREIGN KEY ("appointment_id") REFERENCES "appointments" ("id");

ALTER TABLE "invoice_items" ADD FOREIGN KEY ("invoice_id") REFERENCES "invoices" ("id");
