spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/clinic_erp
    username: clinic_user
    password: clinic_pass
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration